#!/usr/bin/env perl

my ($arg) = @ARGV;
if (length($arg) < 1) {
    print "No arguments given. Please specify the file to edit\n";
    exit();
}

if ($arg =~ /^todo$/) {
    system("grep --color \"TODO\" cs*/notes.md");
    exit();
}

$filename = "$arg/notes.md";

open my $fh, '<', $filename;
read $fh, my $string, -s $fh;
close $fh;

push (@matches,$&) while($string =~ /#Lecture (\d)+/g );
@matches[-1] =~ m/(\d+)$/;
$lecture = int($1) + 1;
$date = `date`;
$title = "#Lecture $lecture - $date";

system("echo \"\n$title\" >> $filename");
system("vim + $filename");
system("git add \"$filename\"");
