#!/usr/bin/env perl

open my $fh, '<', "notes.md";
read $fh, my $string, -s $fh;
close $fh;

push (@matches,$&) while($string =~ /#Lecture (\d)+/g );
@matches[-1] =~ m/(\d+)$/;
$lecture = int($1) + 1;
$date = `date`;
print "#Lecture $lecture - $date";
